export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#022448',
        'on-primary': '#ffffff',
        'primary-container': '#1e3a5f',
        'on-primary-container': '#8aa4cf',
        secondary: '#00677d',
        'on-secondary': '#ffffff',
        'secondary-container': '#50d9fe',
        'on-secondary-container': '#005c70',
        surface: '#faf9fc',
        'surface-dim': '#dad9dd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f7',
        'surface-container': '#eeedf1',
        'surface-container-high': '#e9e7eb',
        'surface-container-highest': '#e3e2e6',
        'on-surface': '#1a1c1e',
        'on-surface-variant': '#43474e',
        outline: '#74777f',
        'outline-variant': '#c4c6cf',
        background: '#faf9fc',
        'on-background': '#1a1c1e',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#adc8f5',
        'on-primary-fixed': '#001c3b',
        'secondary-fixed': '#b3ebff',
        'secondary-fixed-dim': '#4cd6fb',
        'on-secondary-fixed': '#001f27',
        'tertiary-fixed': '#ffddb2',
        'on-tertiary-fixed': '#291800',
        'tertiary-container': '#503300',
        'on-tertiary-container': '#c69b5f',
        'surface-variant': '#e3e2e6',
        'inverse-surface': '#2f3033',
        'inverse-on-surface': '#f1f0f4',
        'inverse-primary': '#adc8f5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        gutter: '24px',
        base: '8px',
        'container-max': '1440px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'headline-md': ['Inter'],
        'body-lg': ['Inter'],
        'display-lg': ['Inter'],
        'headline-lg': ['Inter'],
        'body-sm': ['Inter'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}